#############################################################################
# Generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#  Nov 17, 2020 02:36:03 PM JST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m51" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x450+501+223
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1063
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    vTcl:copy_lock $top
    entry $top.ent47 \
        -background white -disabledbackground #f0f0f0f0f0f0 \
        -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 34 
    vTcl:DefineAlias "$top.ent47" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab54 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {h k l：} 
    vTcl:DefineAlias "$top.lab54" "Label1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent55 \
        -background white -disabledbackground #f0f0f0f0f0f0 \
        -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 34 
    vTcl:DefineAlias "$top.ent55" "Entry1_1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent56 \
        -background white -disabledbackground #f0f0f0f0f0f0 \
        -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 34 
    vTcl:DefineAlias "$top.ent56" "Entry1_2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab58 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Qx Qy：} 
    vTcl:DefineAlias "$top.lab58" "Label1_1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent59 \
        -background white -disabledbackground #f0f0f0f0f0f0 \
        -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 34 
    vTcl:DefineAlias "$top.ent59" "Entry1_3" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent60 \
        -background white -disabledbackground #f0f0f0f0f0f0 \
        -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 34 
    vTcl:DefineAlias "$top.ent60" "Entry1_4" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab65 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 組成： 
    vTcl:DefineAlias "$top.lab65" "Label1_1_1" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra45 \
        -borderwidth 1 -background $vTcl(actual_gui_bg) -height 45 -width 105 
    vTcl:DefineAlias "$top.fra45" "GaN composi input" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra45
    label $site_3_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text GaN： 
    vTcl:DefineAlias "$site_3_0.lab46" "Label1_1_1_1_2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent47 \
        -background white -disabledbackground #f0f0f0f0f0f0 \
        -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 34 
    vTcl:DefineAlias "$site_3_0.ent47" "Entry1_5_1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {[%]} 
    vTcl:DefineAlias "$site_3_0.lab49" "Label1_1_1_2_1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab46 \
        -in $site_3_0 -x 0 -y 0 -width 48 -relwidth 0 -height 51 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $site_3_0.ent47 \
        -in $site_3_0 -x 40 -y 10 -width 34 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 70 -y 0 -width 32 -relwidth 0 -height 51 \
        -relheight 0 -anchor nw -bordermode ignore 
    menu $top.m51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -borderwidth 10 -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    frame $top.fra52 \
        -borderwidth 1 -background $vTcl(actual_gui_bg) -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 105 
    vTcl:DefineAlias "$top.fra52" "AlN composi input_1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra52
    label $site_3_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text AlN： 
    vTcl:DefineAlias "$site_3_0.lab46" "Label1_1_1_1_2_1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent47 \
        -background white -disabledbackground #f0f0f0f0f0f0 \
        -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 34 
    vTcl:DefineAlias "$site_3_0.ent47" "Entry1_5_1_1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {[%]} 
    vTcl:DefineAlias "$site_3_0.lab49" "Label1_1_1_2_1_1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab46 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.457 -height 0 \
        -relheight 1.133 -anchor nw -bordermode ignore 
    place $site_3_0.ent47 \
        -in $site_3_0 -x 40 -y 10 -width 34 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 70 -y 0 -width 32 -relwidth 0 -height 51 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra53 \
        -borderwidth 1 -background $vTcl(actual_gui_bg) -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 105 
    vTcl:DefineAlias "$top.fra53" "InN composi input_1_1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra53
    label $site_3_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text InN： 
    vTcl:DefineAlias "$site_3_0.lab46" "Label1_1_1_1_2_1_1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent47 \
        -background white -disabledbackground #f0f0f0f0f0f0 \
        -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 34 
    vTcl:DefineAlias "$site_3_0.ent47" "Entry1_5_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {[%]} 
    vTcl:DefineAlias "$site_3_0.lab49" "Label1_1_1_2_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab46 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.457 -height 0 \
        -relheight 1.133 -anchor nw -bordermode ignore 
    place $site_3_0.ent47 \
        -in $site_3_0 -x 40 -y 10 -width 34 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 70 -y 0 -width 32 -relwidth 0 -height 51 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.ent47 \
        -in $top -x 70 -y 50 -width 34 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 10 -y 40 -width 64 -relwidth 0 -height 51 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent55 \
        -in $top -x 170 -y 50 -width 34 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent56 \
        -in $top -x 120 -y 50 -width 34 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab58 \
        -in $top -x 10 -y 90 -width 64 -relwidth 0 -height 51 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent59 \
        -in $top -x 70 -y 100 -width 34 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent60 \
        -in $top -x 170 -y 100 -width 34 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab65 \
        -in $top -x 10 -y 150 -width 64 -relwidth 0 -height 51 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra45 \
        -in $top -x 70 -y 150 -width 105 -relwidth 0 -height 45 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra52 \
        -in $top -x 180 -y 150 -width 105 -relwidth 0 -height 45 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra53 \
        -in $top -x 290 -y 150 -width 105 -relwidth 0 -height 45 -relheight 0 \
        -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

