#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Nov 15, 2020 08:28:37 PM JST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import form_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    form_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    form_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+660+210")
        top.minsize(120, 1)
        top.maxsize(3844, 1063)
        top.resizable(1,  1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.117, rely=0.111, height=31, relwidth=0.057)
        self.Entry1.configure(background="white")
        self.Entry1.configure(cursor="fleur")
        self.Entry1.configure(disabledbackground="#f0f0f0f0f0f0")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.017, rely=0.089, height=51, width=64)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''h k l：''')

        self.Entry1_1 = tk.Entry(top)
        self.Entry1_1.place(relx=0.283, rely=0.111, height=31, relwidth=0.057)
        self.Entry1_1.configure(background="white")
        self.Entry1_1.configure(disabledbackground="#f0f0f0f0f0f0")
        self.Entry1_1.configure(disabledforeground="#a3a3a3")
        self.Entry1_1.configure(font="TkFixedFont")
        self.Entry1_1.configure(foreground="#000000")
        self.Entry1_1.configure(highlightbackground="#d9d9d9")
        self.Entry1_1.configure(highlightcolor="black")
        self.Entry1_1.configure(insertbackground="black")
        self.Entry1_1.configure(selectbackground="blue")
        self.Entry1_1.configure(selectforeground="white")

        self.Entry1_2 = tk.Entry(top)
        self.Entry1_2.place(relx=0.2, rely=0.111, height=31, relwidth=0.057)
        self.Entry1_2.configure(background="white")
        self.Entry1_2.configure(disabledbackground="#f0f0f0f0f0f0")
        self.Entry1_2.configure(disabledforeground="#a3a3a3")
        self.Entry1_2.configure(font="TkFixedFont")
        self.Entry1_2.configure(foreground="#000000")
        self.Entry1_2.configure(highlightbackground="#d9d9d9")
        self.Entry1_2.configure(highlightcolor="black")
        self.Entry1_2.configure(insertbackground="black")
        self.Entry1_2.configure(selectbackground="blue")
        self.Entry1_2.configure(selectforeground="white")

        self.Label1_1 = tk.Label(top)
        self.Label1_1.place(relx=0.017, rely=0.2, height=51, width=64)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#d9d9d9")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''Qx Qy：''')

        self.Entry1_3 = tk.Entry(top)
        self.Entry1_3.place(relx=0.117, rely=0.222, height=31, relwidth=0.057)
        self.Entry1_3.configure(background="white")
        self.Entry1_3.configure(disabledbackground="#f0f0f0f0f0f0")
        self.Entry1_3.configure(disabledforeground="#a3a3a3")
        self.Entry1_3.configure(font="TkFixedFont")
        self.Entry1_3.configure(foreground="#000000")
        self.Entry1_3.configure(highlightbackground="#d9d9d9")
        self.Entry1_3.configure(highlightcolor="black")
        self.Entry1_3.configure(insertbackground="black")
        self.Entry1_3.configure(selectbackground="blue")
        self.Entry1_3.configure(selectforeground="white")

        self.Entry1_4 = tk.Entry(top)
        self.Entry1_4.place(relx=0.283, rely=0.222, height=31, relwidth=0.057)
        self.Entry1_4.configure(background="white")
        self.Entry1_4.configure(disabledbackground="#f0f0f0f0f0f0")
        self.Entry1_4.configure(disabledforeground="#a3a3a3")
        self.Entry1_4.configure(font="TkFixedFont")
        self.Entry1_4.configure(foreground="#000000")
        self.Entry1_4.configure(highlightbackground="#d9d9d9")
        self.Entry1_4.configure(highlightcolor="black")
        self.Entry1_4.configure(insertbackground="black")
        self.Entry1_4.configure(selectbackground="blue")
        self.Entry1_4.configure(selectforeground="white")

        self.Entry1_5 = tk.Entry(top)
        self.Entry1_5.place(relx=0.2, rely=0.356, height=31, relwidth=0.057)
        self.Entry1_5.configure(background="white")
        self.Entry1_5.configure(disabledbackground="#f0f0f0f0f0f0")
        self.Entry1_5.configure(disabledforeground="#a3a3a3")
        self.Entry1_5.configure(font="TkFixedFont")
        self.Entry1_5.configure(foreground="#000000")
        self.Entry1_5.configure(highlightbackground="#d9d9d9")
        self.Entry1_5.configure(highlightcolor="black")
        self.Entry1_5.configure(insertbackground="black")
        self.Entry1_5.configure(selectbackground="blue")
        self.Entry1_5.configure(selectforeground="white")

        self.Entry1_6 = tk.Entry(top)
        self.Entry1_6.place(relx=0.35, rely=0.356, height=31, relwidth=0.057)
        self.Entry1_6.configure(background="white")
        self.Entry1_6.configure(disabledbackground="#f0f0f0f0f0f0")
        self.Entry1_6.configure(disabledforeground="#a3a3a3")
        self.Entry1_6.configure(font="TkFixedFont")
        self.Entry1_6.configure(foreground="#000000")
        self.Entry1_6.configure(highlightbackground="#d9d9d9")
        self.Entry1_6.configure(highlightcolor="black")
        self.Entry1_6.configure(insertbackground="black")
        self.Entry1_6.configure(selectbackground="blue")
        self.Entry1_6.configure(selectforeground="white")

        self.Entry1_7 = tk.Entry(top)
        self.Entry1_7.place(relx=0.5, rely=0.356, height=31, relwidth=0.057)
        self.Entry1_7.configure(background="white")
        self.Entry1_7.configure(disabledbackground="#f0f0f0f0f0f0")
        self.Entry1_7.configure(disabledforeground="#a3a3a3")
        self.Entry1_7.configure(font="TkFixedFont")
        self.Entry1_7.configure(foreground="#000000")
        self.Entry1_7.configure(highlightbackground="#d9d9d9")
        self.Entry1_7.configure(highlightcolor="black")
        self.Entry1_7.configure(insertbackground="black")
        self.Entry1_7.configure(selectbackground="blue")
        self.Entry1_7.configure(selectforeground="white")

        self.Label1_1_1 = tk.Label(top)
        self.Label1_1_1.place(relx=0.017, rely=0.333, height=51, width=64)
        self.Label1_1_1.configure(activebackground="#f9f9f9")
        self.Label1_1_1.configure(activeforeground="black")
        self.Label1_1_1.configure(background="#d9d9d9")
        self.Label1_1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1_1.configure(foreground="#000000")
        self.Label1_1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1_1.configure(highlightcolor="black")
        self.Label1_1_1.configure(text='''組成：''')

        self.Label1_1_1_1 = tk.Label(top)
        self.Label1_1_1_1.place(relx=0.15, rely=0.333, height=51, width=34)
        self.Label1_1_1_1.configure(activebackground="#f9f9f9")
        self.Label1_1_1_1.configure(activeforeground="black")
        self.Label1_1_1_1.configure(background="#d9d9d9")
        self.Label1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1_1_1.configure(foreground="#000000")
        self.Label1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1_1_1.configure(highlightcolor="black")
        self.Label1_1_1_1.configure(text='''GaN：''')

        self.Label1_1_1_2 = tk.Label(top)
        self.Label1_1_1_2.place(relx=0.25, rely=0.333, height=51, width=24)
        self.Label1_1_1_2.configure(activebackground="#f9f9f9")
        self.Label1_1_1_2.configure(activeforeground="black")
        self.Label1_1_1_2.configure(background="#d9d9d9")
        self.Label1_1_1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_1_1_2.configure(foreground="#000000")
        self.Label1_1_1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_1_1_2.configure(highlightcolor="black")
        self.Label1_1_1_2.configure(text='''[%]''')

        self.Label1_1_1_1_1 = tk.Label(top)
        self.Label1_1_1_1_1.place(relx=0.3, rely=0.333, height=51, width=34)
        self.Label1_1_1_1_1.configure(activebackground="#f9f9f9")
        self.Label1_1_1_1_1.configure(activeforeground="black")
        self.Label1_1_1_1_1.configure(background="#d9d9d9")
        self.Label1_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1_1_1_1.configure(foreground="#000000")
        self.Label1_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1_1_1_1.configure(highlightcolor="black")
        self.Label1_1_1_1_1.configure(text='''AlN：''')

if __name__ == '__main__':
    vp_start_gui()





