#############################################################################
# Generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#  Nov 15, 2020 08:28:36 PM JST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 600x450+660+210
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1063
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    vTcl:copy_lock $top
    entry $top.ent47 \
        -background white -disabledbackground #f0f0f0f0f0f0 \
        -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 34 
    vTcl:DefineAlias "$top.ent47" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab54 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text {h k l：} 
    vTcl:DefineAlias "$top.lab54" "Label1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent55 \
        -background white -disabledbackground #f0f0f0f0f0f0 \
        -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 34 
    vTcl:DefineAlias "$top.ent55" "Entry1_1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent56 \
        -background white -disabledbackground #f0f0f0f0f0f0 \
        -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 34 
    vTcl:DefineAlias "$top.ent56" "Entry1_2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab58 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Qx Qy：} 
    vTcl:DefineAlias "$top.lab58" "Label1_1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent59 \
        -background white -disabledbackground #f0f0f0f0f0f0 \
        -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 34 
    vTcl:DefineAlias "$top.ent59" "Entry1_3" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent60 \
        -background white -disabledbackground #f0f0f0f0f0f0 \
        -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 34 
    vTcl:DefineAlias "$top.ent60" "Entry1_4" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent61 \
        -background white -disabledbackground #f0f0f0f0f0f0 \
        -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 34 
    vTcl:DefineAlias "$top.ent61" "Entry1_5" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent62 \
        -background white -disabledbackground #f0f0f0f0f0f0 \
        -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 34 
    vTcl:DefineAlias "$top.ent62" "Entry1_6" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent63 \
        -background white -disabledbackground #f0f0f0f0f0f0 \
        -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 34 
    vTcl:DefineAlias "$top.ent63" "Entry1_7" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab65 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 組成： 
    vTcl:DefineAlias "$top.lab65" "Label1_1_1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab66 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text GaN： 
    vTcl:DefineAlias "$top.lab66" "Label1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab67 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {[%]} 
    vTcl:DefineAlias "$top.lab67" "Label1_1_1_2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab68 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text AlN： 
    vTcl:DefineAlias "$top.lab68" "Label1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.ent47 \
        -in $top -x 0 -relx 0.117 -y 0 -rely 0.111 -width 34 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.089 -width 0 -relwidth 0.107 \
        -height 0 -relheight 0.113 -anchor nw -bordermode ignore 
    place $top.ent55 \
        -in $top -x 0 -relx 0.283 -y 0 -rely 0.111 -width 34 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent56 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.111 -width 34 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab58 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.2 -width 0 -relwidth 0.107 \
        -height 0 -relheight 0.113 -anchor nw -bordermode ignore 
    place $top.ent59 \
        -in $top -x 0 -relx 0.117 -y 0 -rely 0.222 -width 34 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent60 \
        -in $top -x 0 -relx 0.283 -y 0 -rely 0.222 -width 34 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent61 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.356 -width 34 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent62 \
        -in $top -x 0 -relx 0.35 -y 0 -rely 0.356 -width 34 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent63 \
        -in $top -x 0 -relx 0.5 -y 0 -rely 0.356 -width 34 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab65 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.333 -width 0 -relwidth 0.107 \
        -height 0 -relheight 0.113 -anchor nw -bordermode ignore 
    place $top.lab66 \
        -in $top -x 0 -relx 0.15 -y 0 -rely 0.333 -width 0 -relwidth 0.057 \
        -height 0 -relheight 0.113 -anchor nw -bordermode ignore 
    place $top.lab67 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.333 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.113 -anchor nw -bordermode ignore 
    place $top.lab68 \
        -in $top -x 0 -relx 0.3 -y 0 -rely 0.333 -width 0 -relwidth 0.057 \
        -height 0 -relheight 0.113 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

